Update pipelines.yaml

diff --git a/.jfrog-pipelines/pipelines.yaml b/.jfrog-pipelines/pipelines.yaml
--- a/.jfrog-pipelines/pipelines.yaml
+++ b/.jfrog-pipelines/pipelines.yaml
@@ -1,36 +1,89 @@
-- name: build
-  type: PowerShell
-  configuration:
-    nodePool: my_windows_node_pool
-    environmentVariables:
-      env1: value1
-      env2:
-        default: value2
-        description: Example Variable
-        values:
-          - value2
-          - value3
-        allowCustom: false
-    runtime:
-      type: image
-      image:
-        auto:
-          language: node
-          versions:
-            - "10.18"
-    inputResources:
-      - name: src
-    integrations:
-      - name: mySlack
-  execution:
-    onExecute:
-      - Push-Location $res_src_resourcePath
-      - npm install
-      - New-Item testresults -Type Directory
-      - New-Item codecoverage -Type Directory
-      - .\node_modules\.bin\mocha --recursive "tests/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=testresults/testresults.xml
-      - .\node_modules\.bin\istanbul --include-all-sources cover -root "routes" node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "tests/**/*.spec.js"
-      - .\node_modules\.bin\istanbul report cobertura --dir codecoverage
-      - save_tests testresults/testresults.xml
-    onSuccess:
-      - send_notification mySlack "build completed"
+name: powershell_pipeline
+steps:
+  - name: first
+    type: PowerShell
+    execution:
+      onStart:
+        - >-
+          echo "onStart can be used to do some setup or initialization of your
+          dependencies to prepare for the execution."
+      onExecute:
+        - >-
+          echo "onExecute is the main section where you would issue your
+          build/test commands"
+        - jfrog --version
+      onSuccess:
+        - >-
+          echo "onSuccess executes if the onStart or onExecute sections
+          completed without errors"
+      onFailure:
+        - >-
+          echo "onFailure executes if either onStart or onExecute end in failure
+          or error."
+      onComplete:
+        - echo "onComplete executes after onSuccess or onFailure"
+  - name: variable_selection
+    type: Bash
+    configuration:
+      inputSteps:
+        - name: first
+      environmentVariables:
+        forceFail:
+          default: 'false'
+          description: set to 'true' to force the step to fail.
+          values:
+            - 'false'
+            - 'true'
+    execution:
+      onStart:
+        - 'if [ ${forceFail} == "true" ]; then exit 1; fi'
+      onExecute:
+        - echo "This step will succeed"
+      onFailure:
+        - echo "step has failed."
+      onSuccess:
+        - echo "step has succeeded."
+      onComplete:
+        - >-
+          echo "onComplete executes regardless of success or failure. forceFail
+          is ${forceFail}"
+  - name: add_run_variable
+    type: Bash
+    configuration:
+      inputSteps:
+        - name: first
+    execution:
+      onStart:
+        - echo "This step will save a value to a run variable."
+      onExecute:
+        - >-
+          add_run_variables step_info="runNumber $run_number, step_name
+          $step_name, pipeline_name $pipeline_name"
+  - name: write_to_resource
+    type: Bash
+    configuration:
+      inputSteps:
+        - name: add_run_variable
+        - name: variable_selection
+      outputResources:
+        - name: intro_bag
+    execution:
+      onStart:
+        - echo "Printing the run variable 'step_info' from previous step"
+        - 'echo "${step_info}"'
+      onExecute:
+        - echo "Updating resource intro_bag with new key/value pairs"
+        - write_output intro_bag "timestamp=$(date +%s)"
+        - 'write_output intro_bag "releaseVersion=${pipeline_name}.${run_number}"'
+        - 'write_output intro_bag "stepInfo=${step_info}"'
+  - name: read_from_resource
+    type: Bash
+    configuration:
+      inputResources:
+        - name: intro_bag
+    execution:
+      onExecute:
+        - echo "printing resource details"
+        - 'echo "Release Version is -- ${res_intro_bag_releaseVersion}"'
+        - 'echo "Release timestamp is -- ${res_intro_bag_timestamp}"'
+        - 'echo "Step Info is -- ${res_intro_bag_stepInfo}"'
